### ISSUE TITLE
jupytercalpoly logo

### ISSUE THREAD

**Issue by eskirk** [jupytercalpoly/team-spirit#13]
It has come to my attention that our current organization logo is a little too robotic/lacking the necessary flair. I propose an amateur's alternative to this problem. 

Any thoughts/input from an actual designer is appreciated
![cal-poly-jupyter](https://cloud.githubusercontent.com/assets/7052378/16160400/cefd1dfa-347c-11e6-90a2-c72751cefd2b.png)

**Comment by eskirk** [comment]
Or this ¯\_(ツ)_/¯
![main-logo](https://cloud.githubusercontent.com/assets/7052378/16166635/ba197b2a-34a1-11e6-8119-5e4421ce1c5c.png)

**Comment by mattb-co** [comment]
Love this idea, maybe we could spice it up a bit? Here's a simple, yet still more extravagant design idea..

![jupyter-calpoly](https://cloud.githubusercontent.com/assets/9501647/16167756/fc73886a-34ad-11e6-8d37-eec49a924938.png)

**Comment by rnetro** [comment]
I think this belongs on some T-shirts :)

**Comment by eskirk** [comment]
ping 🔔

**Comment by eskirk** [comment]
ping @willingc 😉

**Comment by willingc** [comment]
@Ruv7 @ellisonbg The interns have put together a pretty cool logo for the summer teams. Would it be possible to get shirts made for the CP folks that uses the latest logo? If so, what would be the best way to do that? Thanks!

**Comment by Ruv7** [comment]
@ellisonbg - whatever happened to the Jupyter branding guidelines? Were those published somewhere we can view?

**Comment by willingc** [comment]
@Ruv7 This was something that was more of a team building idea than anything that is a rush. It could be as simple as buying t-shirt transfer paper from Staples and use that for putting on the shirts. Branding guidelines are probably in the jupyter/design repo.

**Comment by willingc** [comment]
[Link to the jupyter/design repo](https://github.com/jupyter/design)

**Comment by Ruv7** [comment]
@willingc I have clicked about in good faith in that repo but can't seem to find branding guidelines. I would like anything promoting Project Jupyter to follow the established protocol. Assuming one exists :)  I will follow up to should make those guidelines more available and known among the team and community...

**Comment by eskirk** [comment]
@willingc tbh I just wanted that logo to be the new `jupytercalpoly` logo instead of the default alien lol ¯\_(ツ)_/¯

**Comment by willingc** [comment]
@Ruv7 Sounds good to me. Your wish is our mission.

Okay, team. Marshmallow challenge of the week: Design a non-Jupyter logo for the Cal Poly summer intern t-shirt logo. Extra points for incorporating salsa (music, dancing, or food). 

Branding guidelines for the marketing guru. 👕 👚 👟 👒 👽 🌔 Logos for all the things ;-)

**Comment by ellisonbg** [comment]
More than willing to purchase the students special team t-shirts :-)

We can use Custom Ink for that too...

Cheers,

Brian

On Fri, Jul 1, 2016 at 2:34 PM, Carol Willing notifications@github.com
wrote:

> @Ruv7 https://github.com/Ruv7 Sounds good to me. Your wish is our
> mission.
> 
> Okay, team. Marshmallow challenge of the week: Design a non-Jupyter logo
> for the Cal Poly summer intern t-shirt logo. Extra points for incorporating
> salsa (music, dancing, or food).
> 
> Branding guidelines for the marketing guru. 👕 👚 👟 👒 👽 🌔 Logos for
> all the things ;-)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jupytercalpoly/team-spirit/issues/13#issuecomment-230052189,
> or mute the thread
> https://github.com/notifications/unsubscribe/AABr0KdmvaEeQBYlpArkafGhaQ619JuJks5qRYffgaJpZM4I4mxz
> .

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Ruv7** [comment]
Awesome! Any guidance on where to find the branding guidelines or is that project still in progress?

**Comment by ellisonbg** [comment]
The closest was some work that Cameron did - Matt, could you contact him
about that stuff?

On Fri, Jul 1, 2016 at 2:41 PM, Ana Ruvalcaba notifications@github.com
wrote:

> Awesome! Any guidance on where to find the branding guidelines or is that
> project still in progress?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jupytercalpoly/team-spirit/issues/13#issuecomment-230053535,
> or mute the thread
> https://github.com/notifications/unsubscribe/AABr0NSqIA7LFp2UITDgEhnftByv3b14ks5qRYlxgaJpZM4I4mxz
> .

## 

Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by eskirk** [comment]
@willingc 
Before:
![screen shot 2016-07-27 at 4 03 07 pm](https://cloud.githubusercontent.com/assets/7052378/17195676/1c49faea-5414-11e6-9b03-405b3fb2524c.png)
After:
![after](https://cloud.githubusercontent.com/assets/7052378/17195688/35d2ff70-5414-11e6-879d-a4f031b6c09f.jpg)

Plz for my sanity

**Comment by Ruv7** [comment]
Good to keep this conversation alive, I think the hold up was whether or not we could get status update on branding parameters. If we are going to publish these to the community we shouldn't be the first to break them! @matt-bowers - are you open to leading that discussion?

**Comment by willingc** [comment]
I do like the after version. I will leave this in @Ruv7's capable hands to guide you :sunny:

**Comment by charnpreetsingh** [comment]
+1 on the JupyterCalPoly Github Organization logo redesign.

**Comment by willingc** [comment]
I am somewhat amused that the after version looks as if Chompy has chomped some bites out of the logo.

**Comment by mattb-co** [comment]
Would a simplified avatar be good to replace the default avatar for now, until we can figure out if there are guidelines to follow or not?

<img width="899" alt="screen shot 2016-07-27 at 5 27 06 pm" src="https://cloud.githubusercontent.com/assets/9501647/17197203/87c776a2-541f-11e6-8bfb-762ad33248ea.png">

**Comment by Ruv7** [comment]
We need to figure out branding before using a variation of the logo.

**Comment by eskirk** [comment]
I yield. I don't care about the logo anymore.

**Comment by Ruv7** [comment]
Bummer. Not trying to be an idea squasher, but this is a gap in our design processes and without a design lead on filling the need we can't move forward.

**Comment by willingc** [comment]
@eskirk :cry: We want you to have a logo. We also want to protect Jupyter's intellectual property. For context, this is the short version of the Python Software Foundation's trademark guidance https://www.python.org/psf/trademarks/ and there is a Working Group to work with folks that wish to use/modify the logo.

If you scan down to the derived works section, that specifies what the PSF feels is acceptable or not. I'm wondering if the summer logo was changed enough perhaps using a "sun" instead of "Jupyter" and planets instead of moons that the logo would be different enough to move forward with. 

As an example, we spent quite a bit of time making sure that legally the new Python packaging logo https://pypi.io/ protected the IP of the PSF logo https://www.python.org/community/logos/

**Comment by cameronoelsen** [comment]
So I was in the process of creating a branding guidelines page right before leaving for the summer, I am pretty sure in the guidelines we stated that there should not be any variation to the logo or any components of the logo (aka anything within the three planets in the jupyter logo). The logo that @matt-bowers posted, with the "cp" next to the Jupyter logo, should comply with our guidelines though @Ruv7. However, I am not sure about the one with the text within the planets and under the jupyter wording. When I get home tonight, I will check to see where these guidelines are stored. Regardless, I should be able to have the page or documentation to you guys by tomorrow!

**Comment by faricacarroll** [comment]
Hey @cameronoelsen! Were you able to find those guidelines?

**Comment by Ruv7** [comment]
No worries if not btw, we just don't want to recreate the wheel if you've already started. Any guidance or thoughts today or tomorrow would be great otherwise we'll get started on creating them. Thanks!

**Comment by mattb-co** [comment]
Hey everyone, so I mocked up another temporary "Jupyter Cal Poly" avatar that we can use in place of the branding guidelines being finished. This one **_will indeed comply_** with the branding guidelines the design team is working on, as it is simply a photo overlay of the inverted single color main logo.

![jupyterslo_sm](https://cloud.githubusercontent.com/assets/9501647/17756254/a11b3286-6493-11e6-83a5-264f30c0538e.png)

This is what it would look like as an avatar:

![jupytercalpoly](https://cloud.githubusercontent.com/assets/9501647/17756264/ada89e9e-6493-11e6-8f65-b09e704638c4.png)

**Comment by eskirk** [comment]
Yes but how would it look on a t-shirt?

**Comment by willingc** [comment]
Might look good on a shirt if the overlay was on a watercolor of the photo. :art:
